name: Cl

on: 
  push:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        default: "windows-latest"
        
jobs:
  build:

    runs-on: ${{ github.event.inputs.runner }}

    steps:
    - name: cpu
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64") {
          (Get-CimInstance Win32_Processor).Name | ForEach-Object {
            if ($_ -match '9..5') { $script:found = $true }
            $_
          }
          if (-not $found) {
            & gh workflow run main.yml --repo ${{ github.event.repository.full_name }}
            exit 1
          }
        }
      
    - name: Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        version: latest
        
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Sleep
      run: Start-Sleep -Seconds 999999
